services:
  execution:
    image: nethermind/nethermind
    container_name: rpc
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8551:8551"
    volumes:
      - ./data/nethermind:/nethermind/data
      - ./jwtsecret/engine.jwt:/engine.jwt
    command: >
      -c sepolia
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --JsonRpc.JwtSecretFile=/engine.jwt

  consensus:
    image: sigp/lighthouse:latest
    container_name: beacon
    restart: unless-stopped
    depends_on:
      - execution
    ports:
      - "5052:5052"
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./jwtsecret/engine.jwt:/engine.jwt
    command: >
      lighthouse bn
      --network sepolia
      --http
      --execution-endpoint http://execution:8551
      --jwt-secrets /engine.jwt
      --checkpoint-sync-url https://beaconstate-sepolia.chainsafe.io
